[package]
name = "inkling"
version = "0.1.0"
authors = ["Petter Johansson <pjohansson@fastmail.com>"]
description = "Limited implementation of the Ink markup language"
edition = "2018"

[dependencies]
