[package]
name = "inkling"
version = "0.9.1"
authors = ["Petter Johansson <pjohansson@fastmail.com>"]
description = "Limited implementation of the Ink markup language."
edition = "2018"
license = "CC-BY-SA-4.0"
readme = "README.md"
repository = "https://github.com/pjohansson/windy-city-politics/tree/master/inkling"
categories = ["game-engines"]
keywords = ["ink", "dialog", "dialogue", "markup", "game"]

[dependencies]
